feat(ci): add publish of package in test pypi and pypi for tags
IGNF/route-graph-generator pull request #30
Opened 2023-02-07 09:25 UTC by jmkerloch

closes #17 

update setup.py because an invalid classifier was used.

2023-02-07 09:46 UTC, lgrd commented
There is a need to change the README.md. Because some links are broken inside https://test.pypi.org/project/r2gg/. Wa could use complete links to github. What do you think of it ?

2023-02-07 10:08 UTC, jmkerloch commented
> There is a need to change the README.md. Because some links are broken inside https://test.pypi.org/project/r2gg/. We could use complete links to github. What do you think of it ?

Yes we could use link to the static documentation webpage.

2023-02-07 13:52 UTC, Guts commented
I find it a bit strange that the maintainer identified on PyPi is a user who doesn't correspond to anything: neither Github organisation, nor legal person, nor physical person.

2023-02-07 15:33 UTC, lgrd commented
> I find it a bit strange that the maintainer identified on PyPi is a user who doesn't correspond to anything: neither Github organisation, nor legal person, nor physical person.

As I said, it is temporary. ;) The goal is to move on the IGN organization, when it will be available.

2023-02-07 16:18 UTC, Guts commented
> > I find it a bit strange that the maintainer identified on PyPi is a user who doesn't correspond to anything: neither Github organisation, nor legal person, nor physical person.
> 
> As I said, it is temporary. ;) The goal is to move on the IGN organization, when it will be available.

Sorry, I was not aware of this saying.

2023-02-27 13:25 UTC, lgrd requested changes

2023-02-28 13:49 UTC, jmkerloch commented on .github/workflows/pypi_publish.yml
> +on: push
Unfortunately we can't publish the same version number, not on `test.pypi` and not on `pypi`. 

The step with `test.pypi` is mainly there to check that there is no issue with package build.

And for the publication on `pypi` it's only done when a tag is used: https://github.com/IGNF/route-graph-generator/pull/30/files#diff-e63c5d93f83e5bdcd906866da663fe90cbb5d5132b0b7b59c546b5c652e36fa9R38

2023-02-28 13:54 UTC, lgrd commented on .github/workflows/pypi_publish.yml
> +on: push
perfect !

2023-02-28 13:55 UTC, lgrd approved these changes

2023-03-01 09:50 UTC, merged